### ISSUE TITLE
Feature Register BE

### ISSUE THREAD

**Issue by Tynab** [Tynab/Jira-Project#44]
Tạo chức năng đăng ký trong application controller (dùng post mapping để tạo mới, dùng phương thức saveObject trong service để insert database), redirect index nếu ghi nhớ đăng nhập ở #46 và chưa logout.
*Chú ý:
- Loại bỏ khoảng trắng, ký tự đặc biệt ở trước email.
- Low case email.
- Encode password.

*Gợi ý: dùng string util của project.

**Comment by tiendat-NTD** [comment]
Commit lộn ở cái #46
