### ISSUE TITLE
Feature Detail BE

### ISSUE THREAD

**Issue by Tynab** [Tynab/Jira-Project#52]
Dùng detail controller đẩy các object đã leak ra từ #34 lên ModelAndView dựa trên các param trong attribute constant.
@macmie2411999 support (leak danh sách object dưới phần comment của issue này khi hoàn tất #34)

**Comment by tiendat-NTD** [comment]
Xong 98% còn thêm sản phẩm vào giỏ hàng nhờ a An review code thêm hộ e nữa là xong full HD ko che nhoaaa <3
